# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTku3WyvrkI7NqLCff4phiqK-NvvtPAM
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load the saved model
loaded_model = pickle.load(open('diabetes_model.sav', 'rb'))

# Load the feature names
feature_names = pd.read_csv('diabetes.csv').drop('Outcome', axis=1).columns
#feature_names = pd.read_csv('diabetes_features.csv').drop('Outcome', axis=1).columns

# Define the app title
st.title('Diabetes Prediction App')

# Create input fields for user input
input_data = {}
for feature in feature_names:
    input_data[feature] = st.number_input(feature)

# Create a prediction button
if st.button('Predict'):
    # Convert input data to NumPy array
    input_array = np.array([input_data[feature] for feature in feature_names])
    # Reshape for model compatibility
    input_reshaped = input_array.reshape(1, -1)

    # Make prediction
    prediction = loaded_model.predict(input_reshaped)[0]

    # Display prediction result
    if prediction == 0:
        st.write('The person is not diabetic')
    else:
        st.write('The person is diabetic')



streamlit run C:\Users\Agri NaRM\anaconda3\Lib\site-packages\ipykernel_launche.py